-- ============================================================================
-- SGI Opera Soluciones - Migración 016
-- Fecha: 2026-06-30
-- Descripción: Sistema dinámico de preguntas para autorreportes (Salud, EPP, Legal)
-- ============================================================================

CREATE TABLE IF NOT EXISTS OS_PREGUNTAS_AUTORREPORTE (
    PA_IDPREGUNTA_PK INT AUTO_INCREMENT PRIMARY KEY,
    PA_TEXTO VARCHAR(500) NOT NULL,
    PA_TIPO ENUM('SELECT', 'RADIO', 'CHECKBOX', 'TEXT') NOT NULL,
    PA_SECCION ENUM('SALUD', 'EPP', 'LEGAL', 'GENERAL') NOT NULL,
    PA_OBLIGATORIA BOOLEAN DEFAULT TRUE,
    PA_ORDEN INT DEFAULT 0,
    PA_ACTIVO BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS OS_OPCIONES_PREGUNTA (
    OP_IDOPCION_PK INT AUTO_INCREMENT PRIMARY KEY,
    PA_IDPREGUNTA_FK INT NOT NULL,
    OP_TEXTO VARCHAR(200) NOT NULL,
    OP_VALOR VARCHAR(100) NOT NULL,
    OP_ORDEN INT DEFAULT 0,
    OP_ACTIVO BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (PA_IDPREGUNTA_FK) REFERENCES OS_PREGUNTAS_AUTORREPORTE(PA_IDPREGUNTA_PK) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS OS_RESPUESTAS_AUTORREPORTE (
    RA_IDRESPUESTA_PK INT AUTO_INCREMENT PRIMARY KEY,
    AR_IDAUTORREPORTE_FK INT NOT NULL,
    PA_IDPREGUNTA_FK INT NOT NULL,
    RA_VALOR TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AR_IDAUTORREPORTE_FK) REFERENCES OS_AUTORREPORTES(AR_IDAUTORREPORTE_PK) ON DELETE CASCADE,
    FOREIGN KEY (PA_IDPREGUNTA_FK) REFERENCES OS_PREGUNTAS_AUTORREPORTE(PA_IDPREGUNTA_PK) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insertar preguntas iniciales
INSERT INTO OS_PREGUNTAS_AUTORREPORTE (PA_IDPREGUNTA_PK, PA_TEXTO, PA_TIPO, PA_SECCION, PA_OBLIGATORIA, PA_ORDEN) VALUES
(1, 'Acepto el tratamiento de mis datos personales y biométricos (fotografía) para el control de asistencia.', 'CHECKBOX', 'LEGAL', TRUE, 1),
(2, '¿Cómo se encuentra de salud el día de hoy?', 'RADIO', 'SALUD', TRUE, 2),
(3, '¿Cuenta con todos sus Elementos de Protección Personal (EPPs)?', 'RADIO', 'EPP', TRUE, 3);

-- Opciones para pregunta de Salud (ID 2)
INSERT INTO OS_OPCIONES_PREGUNTA (PA_IDPREGUNTA_FK, OP_TEXTO, OP_VALOR, OP_ORDEN) VALUES
(2, 'Bien', 'BIEN', 1),
(2, 'Regular', 'REGULAR', 2),
(2, 'Mal', 'MAL', 3);

-- Opciones para EPP (ID 3)
INSERT INTO OS_OPCIONES_PREGUNTA (PA_IDPREGUNTA_FK, OP_TEXTO, OP_VALOR, OP_ORDEN) VALUES
(3, 'Sí', 'SI', 1),
(3, 'No', 'NO', 2);
