-- ============================================================================
-- SGI Opera Soluciones - Migración 018
-- Fecha: 2026-07-08
-- Descripción: Creación de tabla para Puestos Físicos y trazabilidad
-- ============================================================================

-- 1. Crear tabla de Puestos (Físicos)
CREATE TABLE IF NOT EXISTS `OS_PUESTOS` (
    PU_IDPUESTO_PK INT AUTO_INCREMENT PRIMARY KEY,
    PU_NOMBRE VARCHAR(150) NOT NULL,
    PU_DIRECCION VARCHAR(255) NULL,
    PU_CIUDAD VARCHAR(100) NULL,
    PU_CENTRO_COSTO VARCHAR(100) NULL,
    PU_NOTAS TEXT NULL,
    PU_ACTIVO BOOLEAN DEFAULT TRUE,
    PU_FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    PU_CREADO_POR INT NULL
) ;

-- 2. Modificar tabla de Usuarios para guardar el Puesto Actual
ALTER TABLE `OS_USUARIOS` 
    ADD COLUMN PU_IDPUESTO_FK INT NULL,
    ADD CONSTRAINT fk_us_puesto FOREIGN KEY (PU_IDPUESTO_FK) REFERENCES `OS_PUESTOS` (PU_IDPUESTO_PK) ON DELETE SET NULL;

-- 3. Crear tabla de Historial de Puestos de Usuarios
CREATE TABLE IF NOT EXISTS `OS_HISTORIAL_PUESTOS` (
    HP_IDHISTORIAL_PK INT AUTO_INCREMENT PRIMARY KEY,
    US_IDUSUARIO_FK INT NOT NULL,
    PU_IDPUESTO_FK INT NOT NULL,
    HP_FECHA_ASIGNACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    HP_CREADO_POR INT NOT NULL,
    HP_NOTAS VARCHAR(255) NULL,
    
    FOREIGN KEY (US_IDUSUARIO_FK) REFERENCES `OS_USUARIOS`(US_IDUSUARIO_PK) ON DELETE CASCADE,
    FOREIGN KEY (PU_IDPUESTO_FK) REFERENCES `OS_PUESTOS`(PU_IDPUESTO_PK) ON DELETE CASCADE,
    INDEX idx_hp_usuario (US_IDUSUARIO_FK),
    INDEX idx_hp_puesto (PU_IDPUESTO_FK)
) ;

-- 4. Modificar tabla de Autorreportes para capturar el snapshot del puesto
ALTER TABLE `OS_AUTORREPORTES`
    ADD COLUMN PU_IDPUESTO_FK INT NULL,
    ADD CONSTRAINT fk_ar_puesto FOREIGN KEY (PU_IDPUESTO_FK) REFERENCES `OS_PUESTOS` (PU_IDPUESTO_PK) ON DELETE SET NULL;
