CREATE TABLE IF NOT EXISTS `OS_MAILER_CONFIG` (
    `ID` int NOT NULL AUTO_INCREMENT,
    `HORA_ENVIO` varchar(10) NOT NULL DEFAULT '08:00',
    `EMAILS` json NOT NULL,
    `ACTIVO` tinyint(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`ID`)
) ;

-- Insertar configuración por defecto si no existe
INSERT INTO `OS_MAILER_CONFIG` (`HORA_ENVIO`, `EMAILS`, `ACTIVO`) 
SELECT '08:00', '[]', 0 
WHERE NOT EXISTS (SELECT 1 FROM `OS_MAILER_CONFIG`);
