ALTER TABLE `OS_MAILER_CONFIG`
ADD COLUMN `SMTP_HOST` varchar(255) DEFAULT NULL,
ADD COLUMN `SMTP_PORT` int DEFAULT NULL,
ADD COLUMN `SMTP_USER` varchar(255) DEFAULT NULL,
ADD COLUMN `SMTP_PASS` varchar(255) DEFAULT NULL,
ADD COLUMN `SMTP_FROM` varchar(255) DEFAULT NULL;
